name: graph_dualrag

# =========================================================
# 基础迭代与截断控制
# =========================================================
max_iter: 5                  # 系统 2 (慢思考) 允许的最大探索跳数
retrieve_topk: 5             # 系统 2 单次意图检索时召回的文档数 (配合 EI 智能体)
#final_topk: 15               # 经过 U 型非破坏性重排后，最终送给大模型进行生成的文档上限
final_topk: 20   
# =========================================================
# 混合复杂度路由 Φ(Q) 超参数
# =========================================================
route_threshold: 0.15        # \tau_{route}: 路由分流阈值 (低于此值走系统1，高于此值走系统2)
alpha: 0.4                   # \alpha: 实体密度的权重系数
beta: 0.6                    # \beta: 检索置信度的权重系数

# =========================================================
#  HEG 动态图谱与拓扑增益推理超参数
# =========================================================
embedding_dim: 384           # 稠密特征向量维度 
sim_threshold: 0.75          # \theta_{sim}: 语义建图门控掩码阈值 (两文档相似度大于此才建立 r_sim 边)
rwr_restart_prob: 0.3        # c: 带重启随机游走 (RWR) 的重启概率
rwr_max_iters: 100           # RWR 游走的最大马尔可夫迭代收敛次数
gamma: 0.6                   # \gamma: 最终拓扑增益融合权重 (调控 RWR拓扑分 与 GraphSAGE特征分 的比例)

retrieve:
    topk: 50
    rerank_topk: 10
    rerank_abl: false

# ${task.base_llm} qwen2.5-72b qwen2.5-7b qwen2.5-7b-ft0 qwen2.5-7b-ft1
infer: ${task.base_llm}
EI: ${task.base_llm}
KS: ${task.base_llm}

abl:
    infer: false
    EI: false
    EI2: false
    KS: false
